name: fui_webview
description: fui WebView control
homepage: https://fui.dev
repository: https://github.com/fui-dev/fui/packages/fui_webview
version: 1.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  webview_flutter: ^4.10.0
  flutter_web_plugins:
    sdk: flutter
  webview_flutter_web: ^0.2.3+2
  webview_flutter_platform_interface: ^2.4.0

  fui:
    path: ../fui/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0