name: fui_lightsensor
description: LightSensor control
homepage: https://fui.dev
repository: https://github.com/fui-dev/fui/packages/fui_lightsensor
version: 0.22.1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  ambient_light: ^0.0.4

  fui:
    path: ../fui/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0