[tool.poetry]
name = "fui-web"
version = "1.0.0"
description = "fui web client in Flutter."
authors = ["Appveyor Systems Inc. <hello@fui.dev>"]
license = "Apache-2.0"

packages = [{ include = "fui_web", from = "src" }]

include = [{ path = "src/fui_web/web/**/*", format = ["sdist", "wheel"] }]

[tool.poetry.urls]
homepage = "https://fui.dev"
repository = "https://github.com/fui-dev/fui"
documentation = "https://fui.dev/docs"

[tool.poetry.dependencies]
python = "^3.8"
fui = { version = "1.0.0" }
fastapi = "*"
uvicorn = { extras = ["standard"], version = "*" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
float_to_top = true
