[tool.poetry]
name = "fui-desktop"
version = "1.0.0"
description = "fui Desktop client in Flutter"
authors = ["Appveyor Systems Inc. <hello@fui.dev>"]
license = "Apache-2.0"

packages = [
    { include = "fui_desktop", from = "src" },
]

include = [
    { path = "src/fui_desktop/app/**/*", format = ["sdist", "wheel"] },
]

[tool.poetry.urls]
homepage = "https://fui.dev"
repository = "https://github.com/fui-dev/fui"
documentation = "https://fui.dev/docs"

[tool.poetry.dependencies]
python = "^3.8"
fui = { version = "1.0.0" }

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.6"
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
float_to_top = true